platform :ios, "8.0"
use_frameworks!

target 'xm2 Native' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON'

  target 'xm2 NativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'xm2 NativeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
